name: 'assign reviewers'

on:
  pull_request

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Assign Reviewers
        uses: khudadad414/auto-reviewers@main

        with:
         token: "${{ secrets.GITHUB_TOKEN }}"
         config: "CODEOWNERS"
