name: Check Reactions on Pr and Issue
on:
  schedule:
    - cron: "0 0 * * 0" # Run at midnight on Sundays
  workflow_dispatch: {} # Allow manual triggering
jobs:
  check-reactions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check Reactions
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            // Check issues with more than 5 reactions
            const issues = await github.paginate(github.issues.listForRepo.endpoint({
              owner,
              repo,
              state: 'open',
            }));

            for (const issue of issues) {
              console.log(`Checking issue #${issue.number}`);
              if (issue.reactions && issue.reactions.total_count > 5) {
                console.log(`Issue #${issue.number} has ${issue.reactions.total_count} reactions`);
                await github.issues.addLabels({
                  owner,
                  repo,
                  issue_number: issue.number,
                  labels: ['more than 5 reactions'],
                });
              }
            }
            // Check pull requests with more than 5 reactions
            const pulls = await github.paginate(github.pulls.list.endpoint({
              owner,
              repo,
              state: 'open',
            }));
            
            for (const pull of pulls) {
              console.log(`Checking pull request #${pull.number}`);
              if (pull.reactions && pull.reactions.total_count > 5) {
                console.log(`Pull request #${pull.number} has ${pull.reactions.total_count} reactions`);
                await github.issues.addLabels({
                  owner,
                  repo,
                  issue_number: pull.number,
                  labels: ['more than 5 reactions'],
                });
              }
            }
